/**
 * Records one real bot play of a game and writes it out as a verification
 * fixture: the exact code, the seed it was played on, the input log the bot
 * produced, and the score replaying that log yields.
 *
 * The fixture is what lets a test (or the deployment spike) exercise the real
 * submitPlay path — verifyPlay against a genuine recorded play — without
 * needing a browser or the AI.
 *
 *   node scripts/make-fixture.mjs <game.js> <out.json> [bot] [seed]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { BOT_SCRIPT } from "../src/bots.ts";
import { runSandboxed } from "../src/sandbox.ts";
import { verifyPlay } from "../src/verify.ts";

const [, , gamePath, outPath, bot = "explorer", seed = "fixture-seed-1"] = process.argv;
if (!gamePath || !outPath) {
  console.error("usage: node scripts/make-fixture.mjs <game.js> <out.json> [bot] [seed]");
  process.exit(1);
}

const code = readFileSync(gamePath, "utf8");

// A generous limit: this is an offline recording, not the production budget.
const run = await runSandboxed({
  code,
  hostScripts: [BOT_SCRIPT],
  expression: `__plBot.run(${JSON.stringify(seed)}, ${JSON.stringify(bot)}, 12345, 10)`,
  timeLimitMs: 30_000,
});
if (!run.ok) throw new Error(`bot play failed: ${run.reason} ${run.detail}`);

const play = JSON.parse(String(run.value));
if (!play.ok) throw new Error(`bot play failed at ${play.stage} tick ${play.tick}: ${play.message}`);

// Replay it exactly as the server will, so the fixture records a score we know
// the production path reproduces rather than one we merely observed.
const verified = await verifyPlay({ code, seed, log: JSON.stringify(play.log), claimedScore: play.score });
if (!verified.ok) throw new Error(`replay disagreed with the recording: ${verified.reason} ${verified.detail}`);

writeFileSync(
  outPath,
  JSON.stringify(
    {
      note: "Generated by packages/replay/scripts/make-fixture.mjs. A real recorded bot play.",
      game: gamePath.replace(/\\/g, "/").split("/").pop(),
      bot,
      seed,
      code,
      log: play.log,
      expectedScore: verified.score,
      expectedTicks: verified.ticks,
      expectedEndReason: verified.endReason,
      expectedHash: verified.hash,
    },
    null,
    2,
  ) + "\n",
  "utf8",
);

console.log(
  `${outPath}: ${bot} on ${seed} -> score ${verified.score}, ${verified.ticks} ticks, ${verified.endReason}, replayed in ${verified.replayMs} ms`,
);
