// Bundles src/prelude.ts into a self-contained IIFE and writes it out as a TS
// string constant (src/generated/prelude.ts). The generated file is committed
// so apps can import it without a build step; test/prelude.test.ts fails if it
// drifts from the source.
import { buildSync } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export function bundlePrelude() {
  const result = buildSync({
    entryPoints: [resolve(root, "src/prelude.ts")],
    bundle: true,
    format: "iife",
    // QuickJS supports ES2020; keep the output within it.
    target: "es2020",
    platform: "neutral",
    minify: false,
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text;
}

export function renderGeneratedModule(code) {
  return (
    "// GENERATED by scripts/build-prelude.mjs from src/prelude.ts. Do not edit.\n" +
    "// Run `pnpm --filter @playloop/runtime build` after changing the runtime.\n" +
    `export const PRELUDE_SOURCE: string = ${JSON.stringify(code)};\n`
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = resolve(root, "src/generated/prelude.ts");
  mkdirSync(dirname(out), { recursive: true });
  const code = bundlePrelude();
  writeFileSync(out, renderGeneratedModule(code));
  console.log(`prelude: ${(code.length / 1024).toFixed(1)} KB -> src/generated/prelude.ts`);
}
