// Bundles the two scripts that run inside a game's sandbox into self-contained
// IIFEs, written out as TS string constants so apps can import them without a
// build step:
//   src/prelude.ts -> src/generated/prelude.ts (PRELUDE_SOURCE): every environment
//   src/host.ts    -> src/generated/host.ts    (HOST_SOURCE):    browser iframe only
// The generated files are committed; test/prelude.test.ts fails if they drift.
import { buildSync } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const BUNDLES = [
  { entry: "src/prelude.ts", out: "src/generated/prelude.ts", constant: "PRELUDE_SOURCE" },
  { entry: "src/host.ts", out: "src/generated/host.ts", constant: "HOST_SOURCE" },
];

export function bundle(entry) {
  const result = buildSync({
    entryPoints: [resolve(root, entry)],
    bundle: true,
    format: "iife",
    // QuickJS supports ES2020; keep the output within it.
    target: "es2020",
    platform: "neutral",
    minify: false,
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text;
}

export function renderGeneratedModule(entry, constant, code) {
  return (
    `// GENERATED by scripts/build-prelude.mjs from ${entry}. Do not edit.\n` +
    "// Run `pnpm --filter @playloop/runtime build` after changing the runtime.\n" +
    `export const ${constant}: string = ${JSON.stringify(code)};\n`
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  for (const { entry, out, constant } of BUNDLES) {
    const target = resolve(root, out);
    mkdirSync(dirname(target), { recursive: true });
    const code = bundle(entry);
    writeFileSync(target, renderGeneratedModule(entry, constant, code));
    console.log(`${constant}: ${(code.length / 1024).toFixed(1)} KB -> ${out}`);
  }
}
