/**
 * Freezes the current prelude as runtime version N.
 *
 *   node scripts/freeze-prelude.mjs
 *
 * Writes src/generated/prelude.vN.ts from today's build, where N is
 * RUNTIME_VERSION. Refuses to overwrite an existing frozen version — that file
 * is the definition of how every play recorded under version N is scored, so
 * changing it would silently re-score plays already in the database.
 *
 * The flow when you change something that affects the simulation is:
 *   1. bump RUNTIME_VERSION in src/contract.ts
 *   2. pnpm --filter @playloop/runtime build
 *   3. node scripts/freeze-prelude.mjs
 *   4. register the new version in src/preludes.ts
 *
 * You should only get here because test/prelude.test.ts told you to.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundle } from "./build-prelude.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Read the version out of the source rather than importing the TS module, so
// this script stays runnable by plain node.
const contract = readFileSync(resolve(root, "src/contract.ts"), "utf8");
const match = contract.match(/export const RUNTIME_VERSION = (\d+);/);
if (!match) throw new Error("Couldn't find RUNTIME_VERSION in src/contract.ts.");
const version = Number(match[1]);

const out = `src/generated/prelude.v${version}.ts`;
const target = resolve(root, out);

if (existsSync(target)) {
  console.error(
    `${out} already exists.\n\n` +
      `Runtime version ${version} is already frozen, and it must stay exactly as it is —\n` +
      `every play recorded under it is scored by these bytes.\n\n` +
      `If you changed the simulation, bump RUNTIME_VERSION in src/contract.ts and run this again.`,
  );
  process.exit(1);
}

const code = bundle("src/prelude.ts");
writeFileSync(
  target,
  `// GENERATED by scripts/freeze-prelude.mjs. Frozen runtime version ${version}.\n` +
    `//\n` +
    `// Do not edit and do not regenerate. Every play recorded under runtime\n` +
    `// version ${version} is replayed by exactly these bytes; changing them would\n` +
    `// silently re-score plays that are already in the database.\n` +
    `export const PRELUDE_V${version}: string = ${JSON.stringify(code)};\n`,
  "utf8",
);

console.log(`Froze runtime version ${version}: ${(code.length / 1024).toFixed(1)} KB -> ${out}`);
console.log(`Now register it in src/preludes.ts.`);
